#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define MAP_WIDTH 24
#define MAP_HEIGHT 24
#define TILE_SIZE 64
#define FOV 60
#define NUM_RAYS SCREEN_WIDTH
#define MAX_DEPTH 30
#define MINIMAP_SCALE 0.1
#define MINIMAP_TILE_SIZE (TILE_SIZE * MINIMAP_SCALE)
#define MINIMAP_PLAYER_SIZE 4

#endif